### ISSUE TITLE
Is a user-specified requirements.txt supported?

### ISSUE THREAD

**Issue by sgbaird** [pypa/flit#456]
It's nice to be able to use something like [pipreqs](https://github.com/bndr/pipreqs) to generate a requirements.txt file, but it's a bit tedious to have to convert this over to the format given by "dependencies" when there's a lot of files. Is there a way to manually supply a requirements.txt file in place of dependencies?

**Comment by sgbaird** [comment]
I'm seeing something like this that might be of use:
https://github.com/benbenbang/req2toml

**Comment by evrial** [comment]
In our projects it is a must because the idea of _abstract and concrete_ dependencies is from 2013.
We are using setup.py and reading requirements.txt and feeding them as list into extras.
```
base_requirements = 'requirements/base.txt'
with open(base_requirements) as f:
    install_requires = [line.strip() for line in f if line.strip()]

ar_extras = 'requirements/abstractresolver.txt'
with open(ar_extras) as f:
    ar_deps = [line.strip() for line in f if line.strip()]

crawler_extras = 'requirements/crawler.txt'
with open(crawler_extras) as f:
    crawler_deps = [line.strip() for line in f if line.strip()]

    'install_requires': install_requires,
    'extras_require': {
        'abstractresolver': ar_deps,
        'crawler': crawler_deps,
    },
```
So in our case and many other projects it is crucial to have a link to dependency FILE to simplify adoption of pyproject.toml
Without that no value to switch because too many of them are repeating and pyproject.toml is very basic.
https://discuss.python.org/t/pyproject-toml-optional-dependencies-redundancy-aka-dry-extras/8428

**Comment by gaborbernat** [comment]
Closing per @takluyver  comment.

**Comment by ThiefMaster** [comment]
I really don't understand why there's so much "hate" against this functionality. Yes, it can be misused (a library pinning its transitive dependencies).

But if you develop an *application* that's meant to be installed in its own environment, then you DO want to pin everything, and a user installing the application should get the exact set of dependencies specified at release time.

And putting 400+ lines of generated metadata (`uv pip compile` output) in a file that's otherwise manually maintained is just awful.
