### ISSUE TITLE
There already is a flit command-line tool

### ISSUE THREAD

**Issue by mikebentley15** [pypa/flit#523]
I don't know the best way to resolve this, but I am the author of another flit command-line tool.  It is also written in python, but not yet released on PyPy.  It is a completely different type of tool.

https://github.com/pruners/flit.git

It's a C++ floating-point compiler reproducibility testing framework.  What that means is that if you compile your C++ code under a different compiler (even the same compiler but a different version) or you change the enabled compiler optimizations, then your numerical code my have reproducibility issues compared to before.

Ultimately, my tool is also called `flit`, the command-line tool is written in python, and would conflict on systems that have both mine and yours installed.

I am open to suggestions on how to resolve this.

**Comment by gaborbernat** [comment]
Seems your tools was created in 2015 September, a few months after our 2015 March. Your tool seems to have its first official release on 2017 26th March - https://github.com/PRUNERS/FLiT/releases/tag/v1.0.0, two full years after March 16th 2019 https://pypi.org/project/flit/0.1/ . 

> , but not yet released on PyPy.

I assume you meant PyPI, because https://www.pypy.org/ is something else.

> Ultimately, my tool is also called `flit`, the command-line tool is written in python, and would conflict on systems that have both mine and yours installed.

Python tooling name reservation is done by holding the PyPi release namespace. So I think if there needs to be a change it should be your tool in this case for both administrative (holding the PyPi namespace) and precedence POV (created/released). That being said probably not easy to do at this point, so I can understand if you don't want to do that. However, I don't see anything actionable on our side.

**Comment by takluyver** [comment]
To be clear, there's no particular rules around who can use what name - this isn't the first time two different things have used the same command name, and it won't be the last. :slightly_smiling_face: It's unfortunate, but there's no easy way to avoid it. In this case, I suspect the target users are different enough that it's not worth trying to rename either project - it will just be a minor headache for a few people who want to install both.

There are rules about who can use what name on PyPI. One rule, really: first come, first served. This project claimed the `flit` name on PyPI years ago, so if you want to publish your FLiT on PyPI as well, you'll need to pick another name. Of course, you're not under any obligation to publish it on PyPI, and the command name doesn't have to match the package name even if you do.

It's amusing that we both have hummingbird logos, though. :laughing:

**Comment by mikebentley15** [comment]
Fair enough.
