### ISSUE TITLE
Signed packages

### ISSUE THREAD

**Issue by tlocke** [pypa/flit#553]
Hi, I'm wondering how flit fits in with signed packages that are uploaded to PyPI. My current workflow for doing a release is:

```
git tag -a x.y.z -m "version x.y.z"
rm -r build; rm -r dist
python -m build
for f in dist/*; do gpg --detach-sign -a $f; done
twine upload dist/*
```
Ideally, signing would be the default in flit, so then a release for me would look like:

```
git tag -a x.y.z -m "version x.y.z"
flit publish
```

Also, thanks for your interesting work on flit.

**Comment by takluyver** [comment]
If [PEP 480](https://peps.python.org/pep-0480/) (Surviving a Compromise of PyPI: End-to-end signing of packages) is accepted, Flit will probably gain support for that signing scheme. I don't plan to add GPG integration, sorry. I'd rather not get into an argument about whether or not it's technically good, but I think very few people use GPG signatures on PyPI, and as you've described, there's a relatively straightforward workaround for people who really do want to upload GPG signatures.

I'd say no even if someone offers to contribute GPG integration, because it would still generate bug reports and questions, and would still lead to extra effort when changing code in the future. (I hope by now this statement is unremarkable - if it's the first time you've heard something like this, I think Brett Cannon explained it well in [this post](https://snarky.ca/setting-expectations-for-open-source-participation/) (ctrl-f for 'puppy' to jump to the bit I mean).
