### ISSUE TITLE
Error when installing flit_core 

### ISSUE THREAD

**Issue by melav99** [pypa/flit#574]
When I try to install the package from the local archive, I face an error in the pyrpoject.toml. However, I am completely clueless as to why I am getting this error. I am running python3.9, pip 20.0.2 on PuTTy through a local Linux computer on a controller.

```
# python3 -m pip install flit_core-3.7.1.tar.gz
Processing ./flit_core-3.7.1.tar.gz
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 2:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppkh3zdy8
       cwd: /tmp/pip-req-build-ad1naz35
  Complete output (1 lines):
  /usr/bin/python3: can't open file '/usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py': [Errno 2] No such file or directory
  ----------------------------------------
ERROR: Command errored out with exit status 2: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppkh3zdy8 Check the logs for full command output.
```

**Comment by takluyver** [comment]
That looks like there might be something wrong with your pip installation, because pip 20.0.2 should certainly have that file:

https://github.com/pypa/pip/tree/20.0.2/src/pip/_vendor/pep517

You might also want to try updating pip (`python3 -m pip install --upgrade pip`). Pip has calendar based versioning, so 20.x is from 2020.
