### ISSUE TITLE
Custom building package with different path

### ISSUE THREAD

**Issue by caligotori** [pypa/flit#577]
Hello, folks

Currently I have an unconventional folder structure that looks like this:

```
...
project/
    └───src/
        └───backend/
            └───project/
                 │   file1.py
                 │   ...
        └───frontend/
            └───project/
                 │   file.js
                 │   ...
...
```

Was wondering if there is a way to specify the `src/backend/project` as `project` when building the package as it happens when its just `src/project`? I was able to build the thing by specifying `project.name = "backend.project"`, but it ends up creating a package named `backend.project` which is fine, but the imports of course will be messed up. So I assumed that specifying `tool.flit.module.name = "project"` would sort of fix the problem. Package would be "misnamed", but everything else would remain the same, but it doesn't as it breaks with:

```
Traceback (most recent call last):
  File "path_to_module", line 5, in <module>
    from project.manage import main
ModuleNotFoundError: No module named 'project.manage'
```

Meaning that that `tool.flit.module.name` does not work as intended (at least for this case). Am I missing something? Apparently flit only accepts 2 layouts `src/project` or `project` with no workarounds?

**Comment by takluyver** [comment]
Sorry, there's no way to configure it for that precise situation. Flit expects your Python package (`project/` containing .py files) to be either in the same directory as `pyproject.toml`, or in a `src/` subdirectory. Those are the only possibilities it checks.

It doesn't insist that pyproject.toml is in the repository root directory, though - so you could have something like:

```
project/
    └───src/
        └───backend/
            │   pyproject.toml
            └───project/
                 │   file1.py
                 │   ...
```

Then you'd run flit from inside the backend directory.

I'm going to close this because I don't plan to implement more config around this - Flit aims for simplicity over supporting all possible cases.
