### ISSUE TITLE
Command line options in pyproject.toml

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#579]
I would like to specify default command line options for my project.  flit would pick these up in addition to what is on the command line.

for example, i might like to have `-f myproject.toml  --format sdist`.  

I see no point in offering a wheel when packages install just fine from an sdist.  

pytest does something like this in pyproject.toml

`[tool.pytest.ini_options]
minversion = "7.1.2"
addopts = "--capture=tee-sys "
`
maybe something like 
'[project]
addopts = "--format sdist"
'

**Comment by takluyver** [comment]
I'm not convinced, I'm afraid.

We've just discussed in #583 why it's probably a good idea to publish both wheels and sdists together. And you can't specify the config file to read inside the config file, for obvious reasons. :wink: 

Flit doesn't have a lot of command line options compared to something like pip or pytest, and those that it does have are meant to be controlled by the user rather than the project. Some of them also have environment variables, giving you a way to set them for all use of Flit (e.g. `FLIT_INSTALL_PYTHON` or `FLIT_INDEX_URL`). And of course, if you really want to run flit with particular options, you can always wrap it in scripts, aliases, makefiles, tox environments, nox sessions, or other such mechanisms to call it with your preferred options.
