### ISSUE TITLE
Motivation to Publish Wheel and sdist

### ISSUE THREAD

**Issue by dougransom** [pypa/flit#583]
I do not understand for the motivation to publish two formats (wheel and sdist).  in the command line document

"Limit to publishing either wheel or sdist. You should normally publish the two formats together.".

Why not just publish the sdist?  Doesn't pip just copy the contents into site-packages and set up the commands/entry points  either way?

**Comment by takluyver** [comment]
For pure Python packages, it doesn't make a *huge* difference, but wheels will install faster, and are easier for tools to inspect their metadata (e.g. to make a dependency graph) because they're reliably static - an sdist has metadata, but the process of building it might produce different metadata (this won't happen with Flit, but tools can't rely on sdist metadata in general).

> Doesn't pip just copy the contents into site-packages and set up the commands/entry points either way?

That's what it does to install a wheel. There are several extra steps if it installs from an sdist:

- Identify the build backend (the `build-system` table in `pyproject.toml`)
- Create a temporary build environment
- Install the build system (e.g. `flit_core`) in the build environment
- Ask the build system (in a subprocess) if it needs any extra dependencies to build this specific package, and if so, install those
- Run the build system (in a new subprocess) to build a wheel
- Install from that wheel

Sdists also often include docs and tests, which wheels don't, so they're typically a bigger download than a wheel (for pure Python packages). E.g. the current version of Flit is 49 kB as a wheel, or 137 kB as an sdist.

Flit makes it really easy to publish wheels and sdists together. Please, don't fight it - publish both by default. Wheels can save time and bandwidth.

(Historical aside: I spent a while arguing that for pure Python packages, actually we should skip *sdists* and just publish wheels, which have all the Python code in a standardised layout. Basically no-one agreed with me on that. :smiley: )

**Comment by dougransom** [comment]
ok sold.  Thanks for the explanation.
