### ISSUE TITLE
Is Hatch officially recommended by PyPA over Flit?

### ISSUE THREAD

**Issue by deepyaman** [pypa/flit#613]
I could have also asked this in pypa/hatch, but given my question stems from an opinionated PR by the maintainer of Hatch, I thought this would get more new information.

I've used Flit on several projects previously, after I first saw it used in https://github.com/tiangolo/typer. Earlier today, I was poking around in https://tiangolo/fastapi, when I noticed that they had migrated to Hatch, and then I saw the changes in https://github.com/tiangolo/fastapi/pull/5240. This PR is worded in a way that makes it seem like PyPA's official recommendation is to use Hatch, and that it provides a lot of advantages over Flit.

1. Is that true?
2. Are there similar reasons to prefer Flit to Hatch? Is one or the other right in certain situations, or is it just personal preference?

**Comment by takluyver** [comment]
I think that FastAPI PR gives a slightly misleading impression. Flit supports the same standards as Hatch, it would have been totally possible to update the metadata to use the `[project]` table ([specification](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/)) and to tell contributors to install things with `pip`, without changing backend. They could also have kept Python 3.6 support if they wanted. :wink: Understandably, though, @ofek included a switch to the newer tool as part of modernisation.

PyPA doesn't recommend any specific tool, as far as I'm aware. At some point I asked that Flit not be presented as the default in the packaging tutorial, because I don't want people to think it's 'the officially recommended tool'. PyPA once appeared to recommend pipenv, and then a lot of people got upset with pipenv.

Certainly Hatch (and [Poetry](https://python-poetry.org/), and [PDM](https://pdm.fming.dev/latest/)) can do more for you than Flit. In particular, all of those tools include functionality to manage an environment associated with your project; Flit leaves that up to you to manage separately.

Is there any remaining reason to use Flit? Perhaps not. :slightly_smiling_face: My best argument would be that for a certain type of simple packaging, Flit is a very simple, boring implementation, with no extra pieces. E.g. if you already manage development environments with virtualenv or conda and want to keep doing that, Flit will never try to create & manage a new environment for you. That's probably a fairly niche requirement, though. :shrug:

**Comment by deepyaman** [comment]
@takluyver @ofek Thank you both for chiming in; much appreciated!
