### ISSUE TITLE
Suggestion: Remove dependency on the requests lib

### ISSUE THREAD

**Issue by taleinat** [pypa/flit#638]
As far as I can tell, requests is only used in one place, to make a simple HTTP GET request:
https://github.com/pypa/flit/blob/ec6e6b7c8994d5e79d0fd951d9e4c26a7c5d9977/flit/validate.py#L55-L57

I suggest replacing that with slightly more complex code using `urllib.request()`, to remove the dependency (and its sub-dependencies).

**Comment by takluyver** [comment]
Is there a particular issue with the dependency? For `flit_core` I try to minimise dependencies because it's needed for bootstrapping a lot of the packaging ecosystem, but the `flit` command line tool is a normal package, and can have dependencies. `requests` is a very common package that lots of Python software uses.

Requests is also used in the `upload` module.

**Comment by taleinat** [comment]
There is no particular issue, just seemed like flit should minimize dependencies. I didn't well enough understand the separation of flit_core, and that does make sense.

Since it's also used for a non-trivial POST request, it's probably a good call to continue using requests.
